name: Check the TypeScript implementation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Support policy: latest and all LTS after Node 22. Older versions are a best-effort basis.
        node-version: ["22.13.0", "latest"]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ matrix.node-version }}
#          cache: "yarn"

      - name: Build and test
        run: |
          yarn install
          yarn run test
          yarn run lint
          yarn run format:check

#      - name: Upload coverage report to codecov.io
#        uses: codecov/codecov-action@v2
#        with:
#          files: "./coverage/lcov.info"
